select 
PASSENGER_ID,COUNTRY_NAME,FIRST_NAME,LAST_NAME,GENDER, AGE, NATIONALITY, AIRPORT_NAME,count(*) 
from DBT_AIR.DBT_SONALI380.SRC_AIRLINE 
group by PASSENGER_ID,COUNTRY_NAME,FIRST_NAME,LAST_NAME,GENDER, AGE, NATIONALITY, AIRPORT_NAME having COUNTRY_NAME in ('United States','Canada','Brazil','Australia')
